version: '3.8'

services:
  app:
    build:
      context: ./php
    container_name: php_fpm
    volumes:
      - ./projects:/var/www/projects

  nginx:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www/projects
      - ./nginx/projects.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app


  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3406:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_ui
    restart: always
    ports:
      - "3407:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db


volumes:
  db_data:
